const $=s=>document.querySelector(s);
const regions={
  '강원특별자치도':['춘천시','원주시','강릉시','속초시','횡성군','철원군','양양군'],'경기도':['평택시','안성시','화성시','이천시','여주시','파주시'],'경상남도':['진주시','밀양시','창녕군','함안군','고성군'],'경상북도':['안동시','상주시','의성군','영천시','예천군'],'광주광역시':['광산구'],'대구광역시':['달성군'],'대전광역시':['유성구'],'부산광역시':['강서구','기장군'],'서울특별시':['광진구','강서구','강남구'],'세종특별자치시':['세종시'],'울산광역시':['울주군'],'인천광역시':['강화군'],'전라남도':['나주시','강진군','해남군','장흥군','보성군','담양군'],'전북특별자치도':['전주시','익산시','김제시','정읍시','완주군'],'제주특별자치도':['제주시','서귀포시'],'충청남도':['아산시','논산시','천안시','공주시','당진시','서산시','태안군','예산군','부여군','보령시'],'충청북도':['청주시','충주시','제천시','괴산군','음성군']
};
let target=null,all=[],windowDays=30,lastAnalysis=null;
const date=d=>{const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,10).replaceAll('-','')};
const parseDate=s=>new Date(`${s.slice(0,4)}-${s.slice(4,6)}-${s.slice(6,8)}T12:00:00`);
const clean=s=>(s||'').replace(/특별자치|특별|광역|도|시|군|구|읍|면|동/g,'');
async function api(path,params={}){const r=await fetch(path+'?'+new URLSearchParams(params));const j=await r.json();if(!r.ok)throw Error(j.detail||j.error||'원자료를 불러오지 못했습니다.');return j}
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function setMessage(s){$('#searchMsg').textContent=s}
$('#province').innerHTML='<option value="">시·도 선택</option>'+Object.keys(regions).map(x=>`<option value="${x}">${x}</option>`).join('');
$('#province').onchange=()=>{$('#city').innerHTML='<option value="">시·군·구 선택</option>'+regions[$('#province').value].map(x=>`<option value="${x}">${x}</option>`).join('')};
$('#searchBtn').onclick=async()=>{const province=$('#province').value,city=$('#city').value,keyword=$('#keyword').value.trim();if(!province||!city){setMessage('시·도와 시·군·구를 먼저 선택하세요.');return}setMessage('KRC 저수지 후보를 찾는 중입니다…');$('#choices').innerHTML='';try{const data=await api('/api/krc/reservoir-codes',{county:province});let items=data.items.filter(x=>clean(x.county).includes(clean(city)));if(keyword)items=items.filter(x=>(x.county+x.facilityName).includes(keyword));items=items.filter((x,i,a)=>a.findIndex(y=>y.facilityCode===x.facilityCode)===i);if(!items.length){setMessage('일치하는 KRC 관리 저수지가 없습니다. 읍·면·동 조건을 비우거나 인접 시·군을 확인하세요.');return}setMessage(`${items.length}개 후보입니다. 저수지 이름을 선택하면 전환 판단을 시작합니다.`);$('#choices').innerHTML=items.slice(0,40).map(x=>`<button data-code="${esc(x.facilityCode)}" data-name="${esc(x.facilityName)}" data-place="${esc(x.county)}">${esc(x.facilityName)} <small>· ${esc(x.county)}</small></button>`).join('');document.querySelectorAll('#choices button').forEach(b=>b.onclick=()=>load({code:b.dataset.code,name:b.dataset.name,place:b.dataset.place}))}catch(e){setMessage('조회 실패: '+e.message)}};
async function load(next=target){if(!next)return;target=next;setMessage('KRC 관측값을 분석하고 있습니다…');try{const to=new Date(),from=new Date(to-(windowDays-1)*86400000);const d=await api('/api/krc/reservoir-levels',{facCode:target.code,from:date(from),to:date(to)});all=d.items.filter(x=>Number.isFinite(x.storageRate)).sort((a,b)=>a.checkDate.localeCompare(b.checkDate));if(all.length<2)throw Error('분석할 관측값이 충분하지 않습니다.');render();setMessage(`KRC 원자료 ${all.length}건으로 분석을 완료했습니다.`)}catch(e){const m=$('#searchMsg');m.textContent='';const s=document.createElement('span');s.textContent='관측자료를 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.';const b=document.createElement('button');b.type='button';b.textContent='다시 시도';b.style.cssText='margin-left:10px;padding:5px 12px;font:inherit;color:#fff;background:#087a77;border:0;border-radius:2px;cursor:pointer';b.onclick=()=>load(target);m.append(s,b)}}
function median(a){if(!a.length)return 0;const b=[...a].sort((x,y)=>x-y),m=Math.floor(b.length/2);return b.length%2?b[m]:(b[m-1]+b[m])/2}
function robustSlope(a){const vals=[];for(let i=0;i<a.length;i++)for(let j=i+1;j<a.length;j++)vals.push((a[j].storageRate-a[i].storageRate)/(j-i));return median(vals)}
function eta(rate,slope,threshold){if(rate<=threshold)return 0;if(slope>=-.02)return null;return Math.ceil((rate-threshold)/(-slope))}
function analysis(a){const latest=a.at(-1),recent=a.slice(-Math.min(8,a.length)),slope=robustSlope(recent),d7=latest.storageRate-recent[0].storageRate;const daily=a.slice(1).map((x,i)=>x.storageRate-a[i].storageRate),history=daily.slice(0,Math.max(0,daily.length-7)),med=median(history),mad=median(history.map(x=>Math.abs(x-med)))||.25,z=(slope-med)/(1.4826*mad),anomaly=Math.min(100,Math.round(Math.max(0,Math.abs(Math.min(0,z))*24)));const rateRisk=Math.max(0,Math.min(100,(65-latest.storageRate)*1.8)),dropRisk=Math.max(0,Math.min(100,(-d7)*5)),missing=Math.max(0,Math.round(((parseDate(latest.checkDate)-parseDate(a[0].checkDate))/86400000+1-a.length)));const quality=Math.max(35,100-Math.min(55,missing*8));const score=Math.round(Math.min(100,.38*rateRisk+.30*dropRisk+.22*anomaly+.10*(100-quality)));let level=score>=70?'danger':score>=42?'watch':'stable',label=score>=70?'즉시 협의 권고':score>=42?'절수 전환 준비':'정기 관측 유지';return {latest,slope,d7,med,mad,z,anomaly,missing,quality,score,level,label,eta50:eta(latest.storageRate,slope,50),eta35:eta(latest.storageRate,slope,35)}}
function etaText(x){return x===0?'이미 도달':x===null?'추세상 미산정':`${x}일`}
function render(){lastAnalysis=analysis(all);const a=lastAnalysis,l=a.latest;$('#workspace').hidden=false;$('#crumb').textContent=`${target.place} › ${target.name}`;$('#decisionBadge').textContent=a.label;$('#decisionBadge').className='badge '+a.level;$('#transitionScore').textContent=a.score;$('#signalMeter').style.width=a.score+'%';$('#signalText').textContent=a.score>=70?'이번 주 공동 절수 협의가 필요한 신호':a.score>=42?'다음 관측 전 절수안 비교가 필요한 신호':'현재는 관측을 유지할 신호';const reasons=[];if(l.storageRate<=50)reasons.push(`저수율 ${l.storageRate.toFixed(1)}%로 관심선(50%) 이하입니다.`);if(a.d7<=-7)reasons.push(`최근 7일 ${a.d7.toFixed(1)}%p 하락해 변화 기준을 넘었습니다.`);if(a.anomaly>=45)reasons.push(`최근 하락 속도가 과거 관측 변화보다 이례적입니다.`);if(a.missing)reasons.push(`분석 기간 중 ${a.missing}일 관측 누락이 있어 판단 신뢰도를 낮췄습니다.`);if(!reasons.length)reasons.push('저수율·최근 변화·이상 신호가 현재 전환 기준보다 낮습니다.');$('#reasonList').innerHTML=reasons.map(x=>`<span>${esc(x)}</span>`).join('');$('#decisionTitle').textContent=a.level==='danger'?'이번 주: 현장 점검과 공동 절수 협의를 시작하세요':a.level==='watch'?'이번 주: 절수안 비교와 담당자 공유를 준비하세요':'이번 주: 다음 관측일까지 추세를 관리하세요';$('#decisionText').textContent=a.level==='danger'?'동일 지역 내 취약 저수지를 함께 비교하고, 급수 여력·수리시설·작물 수요를 확인한 뒤 협의 기록을 남기세요.':a.level==='watch'?'지금부터 10%·20% 절수안의 전환 지연 효과를 비교하고, 다음 관측에서 하락이 이어지면 협의 단계로 올리세요.':'관측값이 갱신될 때까지 변화를 저장해 두고, 급격한 하락 신호가 생기면 즉시 재분석하세요.';$('#latestRate').textContent=l.storageRate.toFixed(1)+'%';$('#latestMeta').textContent=`${l.checkDate} 관측 · 수위 ${l.waterLevelM.toFixed(2)}m`;$('#delta7').textContent=(a.d7>0?'+':'')+a.d7.toFixed(1)+'%p';$('#deltaMeta').textContent=`강건 일 추세 ${a.slope.toFixed(2)}%p/일`;$('#attentionEta').textContent=etaText(a.eta50);$('#attentionMeta').textContent='현재 하락 추세 유지 가정';$('#warningEta').textContent=etaText(a.eta35);$('#warningMeta').textContent='현재 하락 추세 유지 가정';document.querySelectorAll('.metrics article').forEach(x=>x.classList.remove('alert'));if(a.eta50!==null&&a.eta50<=14)$('#attentionEta').closest('article').classList.add('alert');if(a.eta35!==null&&a.eta35<=30)$('#warningEta').closest('article').classList.add('alert');$('#quality').textContent=`데이터 신뢰 상태: KRC 원자료 ${all.length}건 · 관측 ${all[0].checkDate} ~ ${l.checkDate} · 누락 ${a.missing}일 · 신뢰도 ${a.quality}/100`;renderEvidence(a);renderChart(all);renderScenario();renderBrief();renderFavorite();$('#workspace').scrollIntoView({behavior:'smooth'})}
function renderEvidence(a){const cards=[['현재 저수율',a.latest.storageRate.toFixed(1)+'%',a.latest.storageRate<=50?'관심선과의 거리 '+(a.latest.storageRate-50).toFixed(1)+'%p':'관심선보다 '+(a.latest.storageRate-50).toFixed(1)+'%p 높음'],['최근 변화',`${a.d7.toFixed(1)}%p / 7일`,a.slope<0?`강건 하락 추세 ${a.slope.toFixed(2)}%p/일`:'하락 추세가 뚜렷하지 않음'],['변화 이상도',`${a.anomaly}/100`,a.anomaly>=45?'과거 일변화 분포와 비교해 주의할 변화':'과거 관측 범위 내 변화'],['데이터 신뢰도',`${a.quality}/100`,a.missing?`${a.missing}일 누락을 반영해 보수적으로 산정`:'분석 기간에 관측 누락 없음']];$('#evidenceCards').innerHTML=cards.map(x=>`<article><small>${x[0]}</small><b>${x[1]}</b><span>${x[2]}</span></article>`).join('')}
function renderChart(a){const svg=$('#chart'),an=lastAnalysis,w=1000,h=370,L=64,R=26,T=23,B=52;
 const d0=parseDate(a[0].checkDate),dayOf=s=>(parseDate(s)-d0)/86400000,obsDays=dayOf(a.at(-1).checkDate);
 const slope=an.slope,latestRate=an.latest.storageRate,falling=slope<-0.02;
 const fcDays=falling?Math.min(an.eta35!=null?an.eta35+3:45,Math.max(14,Math.round(obsDays*1.2)),75):0;
 const totalDays=Math.max(obsDays+fcDays,obsDays||1),v=a.map(x=>x.storageRate),endRate=falling?latestRate+slope*fcDays:latestRate;
 const min=Math.max(0,Math.min(20,Math.floor(Math.min(...v,endRate)/10)*10)),max=Math.max(80,Math.ceil(Math.max(...v)/10)*10);
 const X=day=>L+(totalDays<=0?0:day/totalDays*(w-L-R)),Y=z=>h-B-(z-min)/(max-min)*(h-T-B);
 const pts=a.map(x=>[X(dayOf(x.checkDate)),Y(x.storageRate)]),line=pts.map((p,i)=>(i?'L':'M')+p[0].toFixed(1)+' '+p[1].toFixed(1)).join(' ');
 const ticks=[min,(min+max)/2,max],grid=ticks.map(t=>`<line x1="${L}" x2="${w-R}" y1="${Y(t).toFixed(1)}" y2="${Y(t).toFixed(1)}" stroke="#dce9e4"/><text x="12" y="${(Y(t)+4).toFixed(1)}" font-size="12" fill="#66807a">${t.toFixed(0)}%</text>`).join('');
 const thr=(n,c,lab)=>n>=min&&n<=max?`<line x1="${L}" x2="${w-R}" y1="${Y(n).toFixed(1)}" y2="${Y(n).toFixed(1)}" stroke="${c}" stroke-dasharray="6 5"/><text x="${w-118}" y="${(Y(n)-5).toFixed(1)}" font-size="12" fill="${c}">${lab} ${n}%</text>`:'';
 const todayX=X(obsDays);let fc='';
 if(falling&&fcDays>0){const fy0=Y(latestRate),fx1=X(totalDays),fy1=Y(Math.max(min,endRate));
  fc=`<path d="M ${todayX.toFixed(1)} ${fy0.toFixed(1)} L ${fx1.toFixed(1)} ${fy1.toFixed(1)}" fill="none" stroke="#087a77" stroke-width="2.5" stroke-dasharray="2 6" opacity=".8"/>`;
  const cross=(t,c,lab)=>{if(latestRate<=t)return '';const days=(latestRate-t)/(-slope);if(days>fcDays)return '';const cx=X(obsDays+days),cy=Y(t);return `<circle cx="${cx.toFixed(1)}" cy="${cy.toFixed(1)}" r="4.5" fill="${c}" stroke="#fff" stroke-width="1.5"/><text x="${cx.toFixed(1)}" y="${(cy-9).toFixed(1)}" font-size="11" font-weight="700" text-anchor="middle" fill="${c}">${lab} D+${Math.ceil(days)}</text>`};
  fc+=cross(50,'#9b6515','관심')+cross(35,'#b83f39','주의');}
 const fmt=s=>`${s.slice(4,6)}.${s.slice(6,8)}`,xl=(day,txt,anc)=>`<text x="${X(day).toFixed(1)}" y="${h-B+18}" font-size="11" text-anchor="${anc}" fill="#66807a">${txt}</text>`;
 const xlabels=xl(0,fmt(a[0].checkDate),'start')+xl(obsDays,'오늘',falling&&fcDays>0?'middle':'end')+(falling&&fcDays>0?xl(totalDays,`+${Math.round(fcDays)}일`,'end'):'');
 const todayMark=`<line x1="${todayX.toFixed(1)}" x2="${todayX.toFixed(1)}" y1="${T}" y2="${h-B}" stroke="#aebfb8" stroke-dasharray="3 3"/>`;
 const area=`<path d="M ${pts[0][0].toFixed(1)} ${h-B} ${pts.map(p=>'L '+p[0].toFixed(1)+' '+p[1].toFixed(1)).join(' ')} L ${pts.at(-1)[0].toFixed(1)} ${h-B}Z" fill="#62c0b233"/>`;
 const dots=pts.map((p,i)=>`<circle cx="${p[0].toFixed(1)}" cy="${p[1].toFixed(1)}" r="${i===pts.length-1?5:3}" fill="#087a77"/>`).join('');
 svg.innerHTML=`${grid}${thr(50,'#9b6515','관심')}${thr(35,'#b83f39','주의')}${todayMark}${area}${fc}<path d="${line}" fill="none" stroke="#087a77" stroke-width="3.5"/>${dots}${xlabels}`;
 const tip=$('#tooltip'),box=svg.getBoundingClientRect();
 svg.onpointermove=e=>{const x=(e.clientX-box.left)/box.width*w;const i=pts.reduce((best,p,j)=>Math.abs(p[0]-x)<Math.abs(pts[best][0]-x)?j:best,0),it=a[i];tip.innerHTML=`<b>${it.checkDate}</b><br>저수율 ${it.storageRate.toFixed(1)}%<br>수위 ${it.waterLevelM.toFixed(2)}m`;tip.hidden=false;tip.style.left=Math.min(box.width-155,Math.max(0,e.clientX-box.left+14))+'px';tip.style.top=Math.max(55,e.clientY-box.top-12)+'px'};
 svg.onpointerleave=()=>tip.hidden=true}
function scenarioEta(threshold,saving){const a=lastAnalysis;if(a.latest.storageRate<=threshold)return 0;if(a.slope>=-.02)return null;return Math.ceil((a.latest.storageRate-threshold)/(-a.slope*(1-saving/100)))}
function renderScenario(){if(!lastAnalysis)return;const a=lastAnalysis,base={rice:5.5,vegetable:4.2,fruit:3.1}[$('#crop').value],stage={normal:1,peak:1.25,late:.72}[$('#stage').value],area=Math.max(100,Number($('#area').value)||1000),demand=Math.round(base*stage*area/1000),baseEta=scenarioEta(35,0);$('#scenarioCards').innerHTML=[0,10,20].map((p,i)=>{const e=scenarioEta(35,p),gain=e!==null&&baseEta!==null?e-baseEta:null;return `<article class="${i===1?'selected':''}"><small>${p}% 절수 가정</small><strong>${etaText(e)}</strong><span>주의선(35%) 도달 추정</span><span class="gain">${p&&gain!==null?`기준안보다 ${gain}일 지연`:'기준 시나리오'}</span></article>`}).join('');$('#demandHint').textContent=`농지 추정 용수 수요: 하루 약 ${demand}㎥ (작물·생육 단계·면적 기반 참고치). 절수율은 저수율 하락 속도에 비례해 반영한 탐색 가정입니다.`}
$('#calcScenario').onclick=renderScenario;
document.querySelectorAll('[data-days]').forEach(b=>b.onclick=()=>{windowDays=+b.dataset.days;document.querySelectorAll('[data-days]').forEach(x=>x.classList.toggle('active',x===b));load()});
$('#compareBtn').onclick=async()=>{if(!target)return;const out=$('#priorityResult'),sp=target.place.indexOf(' '),province=target.place.slice(0,sp),city=target.place.slice(sp+1);out.textContent='같은 시·군 저수지를 분석 중입니다…';try{if(!window.mulsallimCountyReservoirs)throw Error('지역 저수지 목록 기능을 불러오지 못했습니다.');const codes=(await window.mulsallimCountyReservoirs(province,city)).slice(0,12),to=new Date(),from=new Date(to-29*86400000);const list=(await Promise.allSettled(codes.map(async c=>{const x=await api('/api/krc/reservoir-levels',{facCode:c.facilityCode,from:date(from),to:date(to)});const values=x.items.filter(v=>Number.isFinite(v.storageRate)).sort((p,q)=>p.checkDate.localeCompare(q.checkDate));if(values.length<2)throw Error('insufficient');const r=analysis(values);return {name:c.facilityName,rate:r.latest.storageRate,delta:r.d7,score:r.score,label:r.label,level:r.level}}))).filter(x=>x.status==='fulfilled').map(x=>x.value).sort((a,b)=>b.score-a.score);if(!list.length)throw Error('비교 가능한 관측값이 없습니다.');out.innerHTML=`<div style="overflow-x:auto"><table><tr><th>순위</th><th>저수지</th><th>저수율</th><th>7일 변화</th><th>전환 신호</th></tr>${list.map((x,i)=>`<tr><td class="rank">${i+1}</td><td>${esc(x.name)}</td><td>${x.rate.toFixed(1)}%</td><td class="${x.level}">${x.delta.toFixed(1)}%p</td><td class="${x.level}">${x.score} · ${x.label}</td></tr>`).join('')}</table></div>`}catch(e){out.textContent='지역 비교를 만들지 못했습니다: '+e.message}};
function brief(){const a=lastAnalysis,l=a.latest;return `[물살림 AI 협의 브리핑]\n대상: ${target.place} ${target.name}\n기준 관측: ${l.checkDate} / 저수율 ${l.storageRate.toFixed(1)}% / 최근 7일 ${a.d7.toFixed(1)}%p\nAI 전환 신호: ${a.score}/100 (${a.label})\n전환 전망: 관심선 ${etaText(a.eta50)}, 주의선 ${etaText(a.eta35)} — 최근 하락 추세 유지 가정\n권고: ${a.level==='danger'?'현장 점검과 공동 절수 협의를 시작합니다.':a.level==='watch'?'10%·20% 절수안을 비교하고 다음 관측에서 재판단합니다.':'정기 관측을 유지하고 급격한 하락 여부를 확인합니다.'}\n근거와 한계: KRC 원자료 ${all.length}건, 누락 ${a.missing}일. 공식 가뭄 예경보·급수 지시를 대체하지 않으며 현장 수요·기상·시설 상태를 함께 확인해야 합니다.`}
function renderBrief(){$('#briefText').textContent=brief().split('\n').slice(1,5).join(' · ')}
$('#copyBtn').onclick=async()=>{try{await navigator.clipboard.writeText(brief());$('#copyBtn').textContent='복사 완료';setTimeout(()=>$('#copyBtn').textContent='브리핑 복사',1200)}catch{alert(brief())}};
$('#downloadBtn').onclick=()=>{const u=URL.createObjectURL(new Blob([brief()],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download=`물살림AI_협의브리핑_${target.name}_${lastAnalysis.latest.checkDate}.txt`;a.click();URL.revokeObjectURL(u)};
function favs(){try{return JSON.parse(localStorage.getItem('mulsallim-favorites')||'[]')}catch{return[]}}
function renderFavorite(){const saved=favs().some(x=>x.code===target.code);$('#favoriteBtn').textContent=saved?'★ 관심 저수지 저장됨':'☆ 관심 저수지 저장'}
$('#favoriteBtn').onclick=()=>{if(!target)return;const f=favs(),i=f.findIndex(x=>x.code===target.code);if(i>=0)f.splice(i,1);else f.push({...target,savedAt:new Date().toISOString()});localStorage.setItem('mulsallim-favorites',JSON.stringify(f));renderFavorite()};
Promise.all([fetch('/api/health').then(r=>r.json()),fetch('model-evaluation.json').then(r=>r.json())]).then(([health,m])=>{$('#apiStatus').textContent=health.krcConfigured?'KRC 원자료 연결됨':'KRC 인증 설정 필요';$('#apiStatus').style.color=health.krcConfigured?'#a8dec9':'#ffc9c0';$('#modelDecision').textContent=m.decision;$('#modelMetrics').innerHTML=`<article><small>${m.baseline.name}</small><strong>MAE ${m.baseline.mae}%p</strong><small>MAPE ${m.baseline.mape}%</small></article><article><small>${m.candidate.name}</small><strong>MAE ${m.candidate.mae}%p</strong><small>MAPE ${m.candidate.mape}%</small></article>`;$('#modelNext').textContent='다음 검증 단계: '+m.next}).catch(()=>{$('#apiStatus').textContent='API 상태 확인 실패';$('#modelDecision').textContent='검증 결과를 불러오지 못했습니다.'});
