/* 물살림 AI v6: location-based KRC reservoir query (31-day rule). */
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),{URL}=require('node:url');
const root=__dirname,port=Number(process.env.PORT||4183),serviceKey=process.env.KRC_SERVICE_KEY;
const types={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8'};
const send=(res,status,body)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'});res.end(JSON.stringify(body))};
const tag=(xml,name)=>{const m=xml.match(new RegExp(`<${name}>\\s*([^<]*?)\\s*</${name}>`));return m?m[1].trim():null};
const parts=xml=>xml.split('<item>').slice(1).map(x=>x.split('</item>')[0]);
const valid=s=>typeof s==='string'&&/^\d{8}$/.test(s);
const days=(a,b)=>(new Date(`${b.slice(0,4)}-${b.slice(4,6)}-${b.slice(6,8)}`)-new Date(`${a.slice(0,4)}-${a.slice(4,6)}-${a.slice(6,8)}`))/86400000;
function endpoint(protocol,feature,params){const u=new URL(`${protocol}://apis.data.go.kr/B552149/reserviorWaterLevel/${feature}/`);for(const[k,v]of Object.entries({serviceKey,pageNo:'1',numOfRows:'9999',...params}))if(v)u.searchParams.set(k,v);return u}
async function krc(feature,params){if(!serviceKey)return{status:503,body:{error:'KRC API 인증 설정이 필요합니다.'}};try{let protocol='http',r=await fetch(endpoint(protocol,feature,params)),xml=await r.text();if(r.status>=500){protocol='https';r=await fetch(endpoint(protocol,feature,params));xml=await r.text()}const reason=tag(xml,'returnReasonCode');if(!r.ok||(reason&&reason!=='00'))return{status:502,body:{error:'KRC API 응답 오류',detail:tag(xml,'returnAuthMsg')||tag(xml,'errMsg')||`HTTP ${r.status}`}};return{status:200,xml}}catch(e){return{status:502,body:{error:'KRC API 호출 실패',detail:e.message}}}}
const map=x=>({facilityCode:tag(x,'fac_code'),facilityName:tag(x,'fac_name'),county:tag(x,'county'),checkDate:tag(x,'check_date'),waterLevelM:Number(tag(x,'water_level')),storageRate:Number(tag(x,'rate'))});
async function levels(q){const code=q.get('facCode'),from=q.get('from'),to=q.get('to');if(!code||!valid(from)||!valid(to)||days(from,to)>366)return{status:400,body:{error:'facCode 및 최대 366일 범위의 from/to(YYYYMMDD)가 필요합니다.'}};const r=await krc('reservoirlevel',{fac_code:code,date_s:from,date_e:to});return r.status===200?{status:200,body:{source:'한국농어촌공사 농촌용수 저수지 수위정보',asOf:new Date().toISOString(),items:parts(r.xml).map(map)}}:r}
async function byCounty(q){const county=q.get('county'),from=q.get('from'),to=q.get('to');if(!county||!valid(from)||!valid(to)||days(from,to)>30)return{status:400,body:{error:'county 및 최대 31일 범위의 from/to(YYYYMMDD)가 필요합니다.'}};const r=await krc('reservoirlevel',{county,date_s:from,date_e:to});return r.status===200?{status:200,body:{source:'한국농어촌공사 농촌용수 저수지 수위정보',asOf:new Date().toISOString(),items:parts(r.xml).map(map)}}:r}
http.createServer(async(req,res)=>{const u=new URL(req.url,`http://${req.headers.host}`);if(u.pathname==='/api/health')return send(res,200,{status:'ok',krcConfigured:Boolean(serviceKey),apiMode:'county-level'});if(u.pathname==='/api/krc/reservoir-levels'){const r=await levels(u.searchParams);return send(res,r.status,r.body)}if(u.pathname==='/api/krc/reservoir-by-county'){const r=await byCounty(u.searchParams);return send(res,r.status,r.body)}const wanted=u.pathname==='/'?'/mulsallim-public-county.html':decodeURIComponent(u.pathname),file=path.resolve(root,'.'+wanted);if(!file.startsWith(root)||!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404);return res.end('Not Found')}res.writeHead(200,{'content-type':types[path.extname(file)]||'application/octet-stream','x-content-type-options':'nosniff'});fs.createReadStream(file).pipe(res)}).listen(port,()=>console.log(`물살림 AI v6: http://localhost:${port}`));
